# Welcome to jekyll-vfolio theme!
#
# This config file is meant for settings that affect your whole website/blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Altback
email:
author: Ravi Gupta
description: Altback creates Digital Art Resources such as Digital Brushes, Textures, Art tips and tricks. You can find Altback on DeviantArt, Youtube and Gumroad.
url: "https://altback.com/" # The base hostname & protocol for your website. Right now its set for local development. Please change it at the time of deployment.
baseurl:
# The baseurl or the directory from where the site is hosted. Right now its set for the root directory. In case of GitHub Pages add '/repo-name' in front of 'baseurl:' without the quotes.
# For example -
# baseurl: /jekyll-vfolio

# Google Analytics
google_analytics: UA-146584013-1


# Build settings
sass:
  sass_dir: css

# Social icons
show_social_icons: true
deviantart_username: altback
youtube_username: channel/UCkiNcZiYgfwUv6bGys_lAqQ
instagram_username:

# Plugins
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num"
